### PR TITLE
Fix/component themes questions list.js

### LINKED ISSUE #71: Remove the commented-out code snippets in the QuestionsList.js
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\Component\Themes\QuestionsList.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

### PR DESCRIPTION
**Pull request by KunalBhat55**
fixes #71

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
@KunalBhat55 This contains the previous changes as well. Can you rebase and push?

**Comment by KunalBhat55** [comment]
Please Check!

**Review by anjula-sack — CHANGES_REQUESTED** [review]
It's still the same @KunalBhat55. `src/Component/Themes/DropToSelectionNew.js` Changes are there.

You can follow this steps.

1. git rest hard upstream/master
2. Do the change
3. Commit
4. git push -f origin <branch-name>

**Comment by KunalBhat55** [comment]
I think you merged the previous PR so the changes are there.
I have created a new PR please check!

**Comment by KunalBhat55** [comment]
I think you merged the previous PR so the changes are there.
I have created a new PR please check!

**Pull request closed without merging**
